spring:
  application:
    name: config
  cloud:
    config:
      server:
        git:
          uri: https://gitee.com/cdz163/config.git
          username: smartcdz@163.com
          password: wcnm1314
#          basedir: E:\Workspaces\springcloud_sell\config\basedir 指定config本地目录
  rabbitmq:
    host: 119.23.247.21
    username: cdz@rabbit
    password: cdz@469176834
    port: 5672
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
management:
  endpoints:
    web:
      exposure:
        include: "*"